package com.sybinal.shop.mapper;

import com.sybinal.shop.model.Logistics;
import com.sybinal.shop.model.LogisticsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Oct 21 12:02:54 CST 2016
     */
    int countByExample(LogisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Oct 21 12:02:54 CST 2016
     */
    int deleteByExample(LogisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Oct 21 12:02:54 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Oct 21 12:02:54 CST 2016
     */
    int insert(Logistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Oct 21 12:02:54 CST 2016
     */
    int insertSelective(Logistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Oct 21 12:02:54 CST 2016
     */
    List<Logistics> selectByExample(LogisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Oct 21 12:02:54 CST 2016
     */
    Logistics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Oct 21 12:02:54 CST 2016
     */
    int updateByExampleSelective(@Param("record") Logistics record, @Param("example") LogisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Oct 21 12:02:54 CST 2016
     */
    int updateByExample(@Param("record") Logistics record, @Param("example") LogisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Oct 21 12:02:54 CST 2016
     */
    int updateByPrimaryKeySelective(Logistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Oct 21 12:02:54 CST 2016
     */
    int updateByPrimaryKey(Logistics record);
    
    int updateByPrimaryOrderNum(Logistics record);
}