package com.sybinal.shop.mapper;

import com.sybinal.shop.model.ArticleCategory;
import com.sybinal.shop.model.ArticleCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleCategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	int countByExample(ArticleCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	int deleteByExample(ArticleCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	int deleteByPrimaryKey(Integer categoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	int insert(ArticleCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	int insertSelective(ArticleCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	List<ArticleCategory> selectByExample(ArticleCategory example);
	
	int selectCountByExample(ArticleCategory example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	ArticleCategory selectByPrimaryKey(Integer categoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	int updateByExampleSelective(@Param("record") ArticleCategory record,
			@Param("example") ArticleCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	int updateByExample(@Param("record") ArticleCategory record, @Param("example") ArticleCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	int updateByPrimaryKeySelective(ArticleCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	int updateByPrimaryKey(ArticleCategory record);
	
	int countByName(ArticleCategory record);
	
	int selectArticleCountByCategory(ArticleCategory record);
}