package com.sybinal.shop.mapper;

import com.sybinal.shop.model.Contect;
import com.sybinal.shop.model.ContectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContectMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contect
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int countByExample(ContectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contect
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int deleteByExample(ContectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contect
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contect
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int insert(Contect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contect
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int insertSelective(Contect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contect
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	List<Contect> selectByExample(ContectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contect
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	Contect selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contect
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Contect record,
			@Param("example") ContectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contect
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int updateByExample(@Param("record") Contect record,
			@Param("example") ContectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contect
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int updateByPrimaryKeySelective(Contect record);
	
	
	int updateByUserId(Contect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contect
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int updateByPrimaryKey(Contect record);
}