package com.sybinal.shop.mapper;

import com.sybinal.shop.model.OrderItem;
import com.sybinal.shop.model.OrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int countByExample(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int deleteByExample(OrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int insert(OrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int insertSelective(OrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	List<OrderItem> selectByExample(OrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	OrderItem selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int updateByExampleSelective(@Param("record") OrderItem record,
			@Param("example") OrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int updateByExample(@Param("record") OrderItem record,
			@Param("example") OrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int updateByPrimaryKeySelective(OrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_item
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int updateByPrimaryKey(OrderItem record);
	
	int updateByQuantity(OrderItem record);
}