package com.sybinal.shop.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sybinal.shop.model.ProductOptionInfo;
import com.sybinal.shop.model.ProductOptionInfoExample;
import com.sybinal.shop.model.ProductOptionRelation;

public interface ProductOptionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_option_info
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    long countByExample(ProductOptionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_option_info
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    int deleteByExample(ProductOptionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_option_info
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_option_info
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    int insert(ProductOptionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_option_info
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    int insertSelective(ProductOptionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_option_info
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    List<ProductOptionInfo> selectByExample(ProductOptionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_option_info
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    ProductOptionInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_option_info
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProductOptionInfo record, @Param("example") ProductOptionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_option_info
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    int updateByExample(@Param("record") ProductOptionInfo record, @Param("example") ProductOptionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_option_info
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    int updateByPrimaryKeySelective(ProductOptionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_option_info
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    int updateByPrimaryKey(ProductOptionInfo record);
    
    /**
     * 根据商品ID查询Oping Value Sku信息
     * @param productId
     * @return
     */
    List<ProductOptionRelation> selectProductOptionInfoByProductId(Integer productId);
    
}