package com.sybinal.shop.mapper;

import com.sybinal.shop.model.ProductImage;
import com.sybinal.shop.model.ProductImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductImageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_image
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int countByExample(ProductImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_image
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int deleteByExample(ProductImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_image
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_image
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int insert(ProductImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_image
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int insertSelective(ProductImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_image
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	List<ProductImage> selectByExampleWithBLOBs(ProductImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_image
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	List<ProductImage> selectByExample(ProductImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_image
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	ProductImage selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_image
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ProductImage record,
			@Param("example") ProductImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_image
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") ProductImage record,
			@Param("example") ProductImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_image
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int updateByExample(@Param("record") ProductImage record,
			@Param("example") ProductImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_image
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int updateByPrimaryKeySelective(ProductImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_image
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(ProductImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_image
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	int updateByPrimaryKey(ProductImage record);
}