package com.sybinal.shop.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sybinal.shop.model.ProductCategory;
import com.sybinal.shop.model.ProductCategoryExample;
import com.sybinal.shop.model.ProductCategoryRelation;

public interface ProductCategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Fri Oct 21 16:26:56 CST 2016
	 */
	long countByExample(ProductCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Fri Oct 21 16:26:56 CST 2016
	 */
	int deleteByExample(ProductCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Fri Oct 21 16:26:56 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Fri Oct 21 16:26:56 CST 2016
	 */
	int insert(ProductCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Fri Oct 21 16:26:56 CST 2016
	 */
	int insertSelective(ProductCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Fri Oct 21 16:26:56 CST 2016
	 */
	List<ProductCategory> selectByExampleWithBLOBs(ProductCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Fri Oct 21 16:26:56 CST 2016
	 */
	List<ProductCategory> selectByExample(ProductCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Fri Oct 21 16:26:56 CST 2016
	 */
	ProductCategory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Fri Oct 21 16:26:56 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ProductCategory record,
			@Param("example") ProductCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Fri Oct 21 16:26:56 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") ProductCategory record,
			@Param("example") ProductCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Fri Oct 21 16:26:56 CST 2016
	 */
	int updateByExample(@Param("record") ProductCategory record, @Param("example") ProductCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Fri Oct 21 16:26:56 CST 2016
	 */
	int updateByPrimaryKeySelective(ProductCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Fri Oct 21 16:26:56 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(ProductCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_category
	 * @mbg.generated  Fri Oct 21 16:26:56 CST 2016
	 */
	int updateByPrimaryKey(ProductCategory record);

	List<ProductCategory> selectAll();
	
	List<ProductCategory> selectProductCategoryAll(ProductCategory record);
	
	int selectProductCategoryCount(ProductCategory record);
	
	ProductCategory selectByUpdateUserId(String updateUserName);
	
	ProductCategory selectProductCategoryContent(Integer id);

	ProductCategory selectProductCategoryContents(Integer pId);

	ProductCategory selectPid();
	
	int selectProductCount(Integer categoryId);
	
	int deleteProductCategoryList(List<Integer> id);
	
	int selectProductName(String name);
	
	int selectProductCategoryName(ProductCategory record);
	
	List<ProductCategoryRelation> selectCategoryRelation(ProductCategoryExample example);
}