package com.sybinal.shop.mapper;

import com.sybinal.shop.model.Article;
import com.sybinal.shop.model.ArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	int countByExample(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	int deleteByExample(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	int insert(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	int insertSelective(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	List<Article> selectByExampleWithBLOBs(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	List<Article> selectByExample(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	Article selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	int updateByExampleSelective(@Param("record") Article record, @Param("example") ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") Article record, @Param("example") ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	int updateByExample(@Param("record") Article record, @Param("example") ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	int updateByPrimaryKeySelective(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	int updateByPrimaryKey(Article record);
	
	List<Article> selectByArticle(Article example);
	
	int selectCountByArticle(Article example);
	
	List<Article> selectAllByCategoryId(@Param("id") int id);
}