package com.sybinal.shop.mapper;

import com.sybinal.shop.model.Wishlist;
import com.sybinal.shop.model.WishlistExample;
import com.sybinal.shop.model.WishlistRelation;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WishlistMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table wishlist
	 *
	 * @mbg.generated Fri Oct 21 10:16:33 CST 2016
	 */
	long countByExample(WishlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table wishlist
	 *
	 * @mbg.generated Fri Oct 21 10:16:33 CST 2016
	 */
	int deleteByExample(WishlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table wishlist
	 *
	 * @mbg.generated Fri Oct 21 10:16:33 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table wishlist
	 *
	 * @mbg.generated Fri Oct 21 10:16:33 CST 2016
	 */
	int insert(Wishlist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table wishlist
	 *
	 * @mbg.generated Fri Oct 21 10:16:33 CST 2016
	 */
	int insertSelective(Wishlist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table wishlist
	 *
	 * @mbg.generated Fri Oct 21 10:16:33 CST 2016
	 */
	List<Wishlist> selectByExample(WishlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table wishlist
	 *
	 * @mbg.generated Fri Oct 21 10:16:33 CST 2016
	 */
	Wishlist selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table wishlist
	 *
	 * @mbg.generated Fri Oct 21 10:16:33 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Wishlist record, @Param("example") WishlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table wishlist
	 *
	 * @mbg.generated Fri Oct 21 10:16:33 CST 2016
	 */
	int updateByExample(@Param("record") Wishlist record, @Param("example") WishlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table wishlist
	 *
	 * @mbg.generated Fri Oct 21 10:16:33 CST 2016
	 */
	int updateByPrimaryKeySelective(Wishlist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table wishlist
	 *
	 * @mbg.generated Fri Oct 21 10:16:33 CST 2016
	 */
	int updateByPrimaryKey(Wishlist record);

	List<WishlistRelation> selectRelationByPrimaryKey(@Param("userId") int userId);

	int selectRelationCountByPrimaryKey(@Param("userId") int userId);
}